### ISSUE TITLE
The problem with autocomplete

### ISSUE THREAD

**Issue by APEXRARE2009** [ryboe/CSS3#216] opened 2024-05-30 18:25 UTC
Autocomplete перестал работать в последнем версии sublime text, исправте пожалуйста.

Заранее спасибо

**Comment by APEXRARE2009** [comment] 2024-05-30 18:28
Hello,

Autofill has stopped working in the latest version of Sublime Text, please fix it.

Thank you in advance.

**Comment by argyleink** [comment] 2024-05-31 15:47
will investigate asap

**Comment by APEXRARE2009** [comment] 2024-06-01 14:32
Thank you very much😄

**Comment by APEXRARE2009** [comment] 2024-06-04 08:54
Hello,
is there any news?

**Comment by Luuk-van-Aggelen** [comment] 2024-06-05 11:18
Following..

**Comment by argyleink** [comment] 2024-06-05 15:37
duplicate of https://github.com/ryboe/CSS3/issues/198

**Closed by argyleink** 2024-06-05 15:37 UTC

**Comment by Luuk-van-Aggelen** [comment] 2024-06-06 07:02
I'm not entirely sure how this links to an issue from a year ago. This always worked perfectly up until last week.

**Comment by emilezeldenrust** [comment] 2024-06-06 08:02
I am also experiencing this problem. Since last week there is something wrong with autocomplete. The colon and semicolon do not appear when you press tab.

**Comment by APEXRARE2009** [comment] 2024-06-09 08:39
The problem remains

**Comment by argyleink** [comment] 2024-06-10 21:32
nothin suspicious looking in the latest release that leads towards autocomplete issues https://github.com/ryboe/CSS3/compare/v2.1.43...master
