### ISSUE TITLE
Completions regression?

### ISSUE THREAD

**Issue by argyleink** [ryboe/CSS3#198] opened 2023-08-01 23:00 UTC
Anyone have completions working that can share with us your dev env?

**Comment by argyleink** [comment] 2023-08-01 23:03
this may be an oldie https://github.com/ryboe/CSS3/issues/27#issuecomment-99142496

**Comment by Luuk-van-Aggelen** [comment] 2024-06-10 08:35
Hi. You've merged this issue with issue #216  and closed that. But if I may be so free, I don't think these tasks are related.

**Comment by vrugtehagel** [comment] 2024-06-10 20:21
@Luuk-van-Aggelen this issue is, I suppose, just vaguely saying "completions are not working" so there's no much of a point having two issues open that both say that (although, there are admittedly more than two…)

@argyleink I actually can't reproduce this - I don't use autocomplete normally (I've got `"auto_complete": false,` in my settings) but commenting that setting out seems to show completions just fine.

![Screen Recording 2024-06-10 at 22 14 41](https://github.com/ryboe/CSS3/assets/41021050/188ad458-c477-4d83-bfd3-a45de7e04bed)

Of course, that doesn't mean the problem doesn't exist; it just means that the regression (if it is one) is a bit more nuanced.

@Luuk-van-Aggelen (or anyone else having the issue) would you mind sharing a bit more details about your setup? Do you have global or syntax-specific settings that could contribute to this problem? Does it still not provide completions for you with all other packages disabled? I'd be happy to look into the issue, but unfortunately can't do much if I don't have the issue myself.

**Comment by kubiqsk** [comment] 2024-06-11 10:28
isn't it because of this?

![image](https://github.com/ryboe/CSS3/assets/20414087/88c32d6b-0e86-4989-91a7-1147d3f53c25)

**Comment by vrugtehagel** [comment] 2024-06-11 11:04
Thanks @kubiqsk, that's very helpful! It's a bit odd that it's complaining about `grey` (and not `gray`), but I recently removed the `gray()` function so this definitely looks like that would be the regression. I think I might've just missed a reference or two; I've opened a PR to remove these as well. @argyleink could you have a look at https://github.com/ryboe/CSS3/pull/220 and see if that resolves the issue?

**Comment by kubiqsk** [comment] 2024-06-11 11:12
Actually, now when you've mentioned it @vrugtehagel , I remember trying to fix that quickly because I thought it was just a typo, so originally it was supposed to be `gray` and this is just my quick hotfix attempt that didn't work and I just left it like that...

**Comment by vrugtehagel** [comment] 2024-06-11 11:14
Cool! Then I reckon the PR should fix it - let's allow @argyleink some time to review this thread and the pull request, and then we should be back to working completions 😄

**Closed** 2024-06-11 16:22 UTC
